name: dagizo_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: none
# publish_to: https://gitlab.com/t6826/pacific/superapps/dagizo_app.git

version: 1.0.0+2


environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2




    #state management
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3

    # core
  dartz: ^0.10.1
  fimber: ^0.6.1
  get_it: ^7.1.3
  easy_localization: ^3.0.0
  after_layout: ^1.1.0

  # network and data

  shared_preferences: ^2.0.8


  # UI
  flutter_screenutil: ^5.3.1
  fluttertoast: ^8.0.7
  flutter_svg: ^1.0.3
  flutter_animator: ^3.1.1
  flutter_spinkit: ^5.0.0
  google_fonts: ^2.2.0
  im_stepper: ^1.0.1+1
  custom_slider: ^0.0.3



  event_bus: ^2.0.0




  # Dev tools
  freezed_annotation:
  injectable: ^1.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.9.2

  change_app_package_name: ^1.0.0

  flutter_native_splash: ^2.1.2+1
  mocktail: ^0.1.0
  very_good_analysis: ^2.4.0
  injectable_generator:
  build_runner:
  freezed:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launch_icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/launch_icon.png"
  fullscreen: true
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

    - assets/translations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Normal.ttf

  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
